TOOLS = [
    {
        "name": "bridge.ping",
        "description": "Ping Pixelorama bridge extension.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "bridge.version",
        "description": "Get Pixelorama version from bridge extension.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "bridge.info",
        "description": "Get bridge protocol and extension info.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "project.create",
        "description": "Create a new project and make it current.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "width": {"type": "integer", "minimum": 1},
                "height": {"type": "integer", "minimum": 1},
                "fill_color": {
                    "description": "RGBA array [r,g,b,a] (0-1 or 0-255) or hex string.",
                    "type": ["array", "string", "object", "null"],
                },
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "project.open",
        "description": "Open a .pxo project file.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}, "replace_empty": {"type": "boolean"}},
            "required": ["path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "project.save",
        "description": "Save current project to .pxo.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}, "include_blended": {"type": "boolean"}},
            "required": ["path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "project.export",
        "description": "Export current project frame to PNG.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
                "split_layers": {"type": "boolean"},
                "trim": {"type": "boolean"},
                "scale": {"type": "integer"},
                "interpolation": {"type": "string"},
            },
            "required": ["path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "project.info",
        "description": "Get current project info.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "project.set_active",
        "description": "Set current frame/layer.",
        "inputSchema": {
            "type": "object",
            "properties": {"frame": {"type": "integer"}, "layer": {"type": "integer"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "project.set_indexed_mode",
        "description": "Enable/disable indexed color mode.",
        "inputSchema": {
            "type": "object",
            "properties": {"enabled": {"type": "boolean"}},
            "required": ["enabled"],
            "additionalProperties": False,
        },
    },
    {
        "name": "layer.list",
        "description": "List layers.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "layer.add",
        "description": "Add a layer above a given index.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "above": {"type": "integer"},
                "name": {"type": "string"},
                "type": {"type": ["string", "integer"]},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "layer.remove",
        "description": "Remove a layer by index.",
        "inputSchema": {
            "type": "object",
            "properties": {"index": {"type": "integer"}},
            "required": ["index"],
            "additionalProperties": False,
        },
    },
    {
        "name": "layer.rename",
        "description": "Rename a layer by index.",
        "inputSchema": {
            "type": "object",
            "properties": {"index": {"type": "integer"}, "name": {"type": "string"}},
            "required": ["index", "name"],
            "additionalProperties": False,
        },
    },
    {
        "name": "layer.move",
        "description": "Move a layer from one index to another.",
        "inputSchema": {
            "type": "object",
            "properties": {"from": {"type": "integer"}, "to": {"type": "integer"}},
            "required": ["from", "to"],
            "additionalProperties": False,
        },
    },
    {
        "name": "frame.list",
        "description": "List frames.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "frame.add",
        "description": "Add a new frame after index.",
        "inputSchema": {
            "type": "object",
            "properties": {"after": {"type": "integer"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "frame.remove",
        "description": "Remove a frame by index.",
        "inputSchema": {
            "type": "object",
            "properties": {"index": {"type": "integer"}},
            "required": ["index"],
            "additionalProperties": False,
        },
    },
    {
        "name": "frame.duplicate",
        "description": "Duplicate a frame by index.",
        "inputSchema": {
            "type": "object",
            "properties": {"index": {"type": "integer"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "frame.move",
        "description": "Move a frame from one index to another.",
        "inputSchema": {
            "type": "object",
            "properties": {"from": {"type": "integer"}, "to": {"type": "integer"}},
            "required": ["from", "to"],
            "additionalProperties": False,
        },
    },
    {
        "name": "pixel.get",
        "description": "Get a pixel color from a Pixel layer.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "x": {"type": "integer"},
                "y": {"type": "integer"},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["x", "y"],
            "additionalProperties": False,
        },
    },
    {
        "name": "pixel.set",
        "description": "Set a pixel color on a Pixel layer.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "x": {"type": "integer"},
                "y": {"type": "integer"},
                "color": {"type": ["array", "string", "object", "null"]},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["x", "y", "color"],
            "additionalProperties": False,
        },
    },
    {
        "name": "canvas.fill",
        "description": "Fill a Pixel layer with a color.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "color": {"type": ["array", "string", "object", "null"]},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["color"],
            "additionalProperties": False,
        },
    },
    {
        "name": "canvas.clear",
        "description": "Clear a Pixel layer (transparent).",
        "inputSchema": {
            "type": "object",
            "properties": {"frame": {"type": "integer"}, "layer": {"type": "integer"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "canvas.resize",
        "description": "Resize canvas with offset.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "width": {"type": "integer"},
                "height": {"type": "integer"},
                "offset_x": {"type": "integer"},
                "offset_y": {"type": "integer"},
            },
            "required": ["width", "height"],
            "additionalProperties": False,
        },
    },
    {
        "name": "canvas.crop",
        "description": "Crop to rectangle (x,y,width,height).",
        "inputSchema": {
            "type": "object",
            "properties": {
                "x": {"type": "integer"},
                "y": {"type": "integer"},
                "width": {"type": "integer"},
                "height": {"type": "integer"},
            },
            "required": ["x", "y", "width", "height"],
            "additionalProperties": False,
        },
    },
    {
        "name": "canvas.snapshot",
        "description": (
            "Get a composited snapshot of all visible layers as a viewable PNG image. "
            "Use this to see what the canvas looks like (visual feedback loop). "
            "Returns the image inline so you can analyze it and continue drawing."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "frame": {"type": "integer"},
                "scale": {
                    "type": "integer",
                    "description": "Scale factor (default 1). Use 2-4 for small canvases to see detail.",
                },
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "palette.list",
        "description": "List palettes.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "palette.select",
        "description": "Select palette by name.",
        "inputSchema": {
            "type": "object",
            "properties": {"name": {"type": "string"}},
            "required": ["name"],
            "additionalProperties": False,
        },
    },
    {
        "name": "palette.create",
        "description": "Create a palette.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "width": {"type": "integer"},
                "height": {"type": "integer"},
                "global": {"type": "boolean"},
            },
            "required": ["name"],
            "additionalProperties": False,
        },
    },
    {
        "name": "palette.delete",
        "description": "Delete a palette by name.",
        "inputSchema": {
            "type": "object",
            "properties": {"name": {"type": "string"}},
            "required": ["name"],
            "additionalProperties": False,
        },
    },
    {
        "name": "draw.line",
        "description": "Draw a line on a Pixel layer.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "x1": {"type": "integer"},
                "y1": {"type": "integer"},
                "x2": {"type": "integer"},
                "y2": {"type": "integer"},
                "color": {"type": ["array", "string", "object", "null"]},
                "thickness": {"type": "integer"},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["x1", "y1", "x2", "y2", "color"],
            "additionalProperties": False,
        },
    },
    {
        "name": "draw.rect",
        "description": "Draw rectangle on a Pixel layer.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "x": {"type": "integer"},
                "y": {"type": "integer"},
                "width": {"type": "integer"},
                "height": {"type": "integer"},
                "color": {"type": ["array", "string", "object", "null"]},
                "fill": {"type": "boolean"},
                "thickness": {"type": "integer"},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["x", "y", "width", "height", "color"],
            "additionalProperties": False,
        },
    },
    {
        "name": "draw.ellipse",
        "description": "Draw ellipse on a Pixel layer.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "x": {"type": "integer"},
                "y": {"type": "integer"},
                "width": {"type": "integer"},
                "height": {"type": "integer"},
                "color": {"type": ["array", "string", "object", "null"]},
                "fill": {"type": "boolean"},
                "thickness": {"type": "integer"},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["x", "y", "width", "height", "color"],
            "additionalProperties": False,
        },
    },
    {
        "name": "draw.erase_line",
        "description": "Erase (transparent) line on a Pixel layer.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "x1": {"type": "integer"},
                "y1": {"type": "integer"},
                "x2": {"type": "integer"},
                "y2": {"type": "integer"},
                "thickness": {"type": "integer"},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["x1", "y1", "x2", "y2"],
            "additionalProperties": False,
        },
    },
    {
        "name": "pixel.replace_color",
        "description": "Replace a color on a Pixel layer.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "from": {"type": ["array", "string", "object", "null"]},
                "to": {"type": ["array", "string", "object", "null"]},
                "tolerance": {"type": "number"},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["from", "to"],
            "additionalProperties": False,
        },
    },
    {
        "name": "selection.clear",
        "description": "Clear selection.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "selection.invert",
        "description": "Invert selection.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "selection.rect",
        "description": "Rectangle selection.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "x": {"type": "integer"},
                "y": {"type": "integer"},
                "width": {"type": "integer"},
                "height": {"type": "integer"},
                "mode": {"type": "string"},
            },
            "required": ["x", "y", "width", "height"],
            "additionalProperties": False,
        },
    },
    {
        "name": "selection.ellipse",
        "description": "Ellipse selection.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "x": {"type": "integer"},
                "y": {"type": "integer"},
                "width": {"type": "integer"},
                "height": {"type": "integer"},
                "mode": {"type": "string"},
            },
            "required": ["x", "y", "width", "height"],
            "additionalProperties": False,
        },
    },
    {
        "name": "selection.lasso",
        "description": "Lasso selection using polygon points.",
        "inputSchema": {
            "type": "object",
            "properties": {"points": {"type": "array"}, "mode": {"type": "string"}},
            "required": ["points"],
            "additionalProperties": False,
        },
    },
    {
        "name": "selection.move",
        "description": "Move selection mask by dx/dy.",
        "inputSchema": {
            "type": "object",
            "properties": {"dx": {"type": "integer"}, "dy": {"type": "integer"}},
            "required": ["dx", "dy"],
            "additionalProperties": False,
        },
    },
    {
        "name": "selection.export_mask",
        "description": "Export selection mask PNG.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}},
            "required": ["path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "symmetry.set",
        "description": "Set symmetry guides and visibility.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "show_x": {"type": "boolean"},
                "show_y": {"type": "boolean"},
                "show_xy": {"type": "boolean"},
                "show_x_minus_y": {"type": "boolean"},
                "x": {"type": "number"},
                "y": {"type": "number"},
                "xy": {"type": "array"},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "batch.exec",
        "description": "Execute multiple bridge calls in a single request.",
        "inputSchema": {
            "type": "object",
            "properties": {"calls": {"type": "array"}},
            "required": ["calls"],
            "additionalProperties": False,
        },
    },
    {
        "name": "project.import.sequence",
        "description": "Import an image sequence as frames.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "paths": {"type": "array"},
                "mode": {"type": "string"},
                "layer": {"type": "integer"},
                "fps": {"type": "number"},
                "durations_ms": {"type": "array"},
            },
            "required": ["paths"],
            "additionalProperties": False,
        },
    },
    {
        "name": "project.import.spritesheet",
        "description": "Import a spritesheet as new project or new layer.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "horizontal": {"type": "integer"},
                "vertical": {"type": "integer"},
                "mode": {"type": "string"},
                "name": {"type": "string"},
                "start_frame": {"type": "integer"},
                "detect_empty": {"type": "boolean"},
            },
            "required": ["path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "pixel.set_many",
        "description": "Set multiple pixels in one call.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "points": {"type": "array"},
                "color": {"type": ["array", "string", "object", "null"]},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["points"],
            "additionalProperties": False,
        },
    },
    {
        "name": "pixel.get_region",
        "description": "Get a region as PNG image (returned as viewable image content). Single layer only.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "x": {"type": "integer"},
                "y": {"type": "integer"},
                "width": {"type": "integer"},
                "height": {"type": "integer"},
                "format": {"type": "string"},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["x", "y", "width", "height"],
            "additionalProperties": False,
        },
    },
    {
        "name": "pixel.set_region",
        "description": "Blit a PNG/raw base64 image into a cel.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "x": {"type": "integer"},
                "y": {"type": "integer"},
                "data": {"type": "string"},
                "format": {"type": "string"},
                "width": {"type": "integer"},
                "height": {"type": "integer"},
                "mode": {"type": "string"},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["data"],
            "additionalProperties": False,
        },
    },
    {
        "name": "animation.tags.list",
        "description": "List animation tags.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "animation.tags.add",
        "description": "Add an animation tag.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "from": {"type": "integer"},
                "to": {"type": "integer"},
                "color": {"type": ["array", "string", "object", "null"]},
                "user_data": {"type": "string"},
            },
            "required": ["name", "from", "to"],
            "additionalProperties": False,
        },
    },
    {
        "name": "animation.tags.update",
        "description": "Update an animation tag by index or name.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "index": {"type": "integer"},
                "name": {"type": "string"},
                "new_name": {"type": "string"},
                "from": {"type": "integer"},
                "to": {"type": "integer"},
                "color": {"type": ["array", "string", "object", "null"]},
                "user_data": {"type": "string"},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "animation.tags.remove",
        "description": "Remove an animation tag by index or name.",
        "inputSchema": {
            "type": "object",
            "properties": {"index": {"type": "integer"}, "name": {"type": "string"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "animation.playback.set",
        "description": "Enable/disable play-only-tags and optionally jump to tag.",
        "inputSchema": {
            "type": "object",
            "properties": {"play_only_tags": {"type": "boolean"}, "tag": {"type": "string"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "tilemap.tileset.list",
        "description": "List tilesets.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "tilemap.tileset.create",
        "description": "Create a tileset.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tile_size": {"type": "array"},
                "name": {"type": "string"},
                "tile_shape": {"type": ["string", "integer"]},
                "add_empty_tile": {"type": "boolean"},
            },
            "required": ["tile_size"],
            "additionalProperties": False,
        },
    },
    {
        "name": "tilemap.tileset.add_tile",
        "description": "Add a tile image to a tileset.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tileset_index": {"type": "integer"},
                "path": {"type": "string"},
                "layer": {"type": "integer"},
                "frame": {"type": "integer"},
                "times_used": {"type": "integer"},
            },
            "required": ["tileset_index", "path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "tilemap.tileset.remove_tile",
        "description": "Remove a tile from a tileset.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tileset_index": {"type": "integer"},
                "tile_index": {"type": "integer"},
                "layer": {"type": "integer"},
                "frame": {"type": "integer"},
            },
            "required": ["tileset_index", "tile_index"],
            "additionalProperties": False,
        },
    },
    {
        "name": "tilemap.tileset.replace_tile",
        "description": "Replace a tile image in a tileset.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tileset_index": {"type": "integer"},
                "tile_index": {"type": "integer"},
                "path": {"type": "string"},
                "layer": {"type": "integer"},
                "frame": {"type": "integer"},
            },
            "required": ["tileset_index", "tile_index", "path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "tilemap.layer.set_tileset",
        "description": "Assign a tileset to a tilemap layer.",
        "inputSchema": {
            "type": "object",
            "properties": {"layer": {"type": "integer"}, "tileset_index": {"type": "integer"}},
            "required": ["tileset_index"],
            "additionalProperties": False,
        },
    },
    {
        "name": "tilemap.layer.set_params",
        "description": "Set tilemap layer parameters.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "place_only_mode": {"type": "boolean"},
                "tile_size": {"type": "array"},
                "tile_shape": {"type": ["string", "integer"]},
                "tile_layout": {"type": ["string", "integer"]},
                "tile_offset_axis": {"type": ["string", "integer"]},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "tilemap.offset.set",
        "description": "Set tilemap offset for a cel.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "frame": {"type": "integer"},
                "x": {"type": "integer"},
                "y": {"type": "integer"},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "tilemap.cell.get",
        "description": "Get tilemap cell data.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "frame": {"type": "integer"},
                "cell_x": {"type": "integer"},
                "cell_y": {"type": "integer"},
            },
            "required": ["cell_x", "cell_y"],
            "additionalProperties": False,
        },
    },
    {
        "name": "tilemap.cell.set",
        "description": "Set tilemap cell data.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "frame": {"type": "integer"},
                "cell_x": {"type": "integer"},
                "cell_y": {"type": "integer"},
                "index": {"type": "integer"},
                "flip_h": {"type": "boolean"},
                "flip_v": {"type": "boolean"},
                "transpose": {"type": "boolean"},
            },
            "required": ["cell_x", "cell_y", "index"],
            "additionalProperties": False,
        },
    },
    {
        "name": "tilemap.cell.clear",
        "description": "Clear tilemap cell.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "frame": {"type": "integer"},
                "cell_x": {"type": "integer"},
                "cell_y": {"type": "integer"},
            },
            "required": ["cell_x", "cell_y"],
            "additionalProperties": False,
        },
    },
    {
        "name": "effect.layer.list",
        "description": "List layer effects.",
        "inputSchema": {
            "type": "object",
            "properties": {"layer": {"type": "integer"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "effect.layer.add",
        "description": "Add a layer effect (shader).",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "shader_path": {"type": "string"},
                "name": {"type": "string"},
                "category": {"type": "string"},
                "params": {"type": "object"},
                "enabled": {"type": "boolean"},
                "validate": {"type": "boolean"},
            },
            "required": ["shader_path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "effect.layer.remove",
        "description": "Remove a layer effect.",
        "inputSchema": {
            "type": "object",
            "properties": {"layer": {"type": "integer"}, "index": {"type": "integer"}},
            "required": ["index"],
            "additionalProperties": False,
        },
    },
    {
        "name": "effect.layer.move",
        "description": "Reorder layer effects.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "from": {"type": "integer"},
                "to": {"type": "integer"},
            },
            "required": ["from", "to"],
            "additionalProperties": False,
        },
    },
    {
        "name": "effect.layer.set_enabled",
        "description": "Enable/disable a layer effect.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "index": {"type": "integer"},
                "enabled": {"type": "boolean"},
            },
            "required": ["index", "enabled"],
            "additionalProperties": False,
        },
    },
    {
        "name": "effect.layer.set_params",
        "description": "Update layer effect parameters.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "index": {"type": "integer"},
                "params": {"type": "object"},
                "validate": {"type": "boolean"},
            },
            "required": ["index", "params"],
            "additionalProperties": False,
        },
    },
    {
        "name": "effect.layer.apply",
        "description": "Apply a layer effect to a cel (bake).",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "frame": {"type": "integer"},
                "index": {"type": "integer"},
                "remove_after": {"type": "boolean"},
            },
            "required": ["index"],
            "additionalProperties": False,
        },
    },
    {
        "name": "effect.shader.apply",
        "description": "Apply a shader directly to a cel.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "frame": {"type": "integer"},
                "shader_path": {"type": "string"},
                "params": {"type": "object"},
                "validate": {"type": "boolean"},
            },
            "required": ["shader_path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "history.undo",
        "description": "Undo last action.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "history.redo",
        "description": "Redo last action.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "three_d.object.list",
        "description": "List 3D objects in a cel.",
        "inputSchema": {
            "type": "object",
            "properties": {"layer": {"type": "integer"}, "frame": {"type": "integer"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "three_d.object.add",
        "description": "Add a 3D object.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "frame": {"type": "integer"},
                "type": {"type": ["string", "integer"]},
                "position": {"type": "array"},
                "rotation": {"type": "array"},
                "rotation_degrees": {"type": "array"},
                "scale": {"type": "array"},
                "visible": {"type": "boolean"},
                "file_path": {"type": "string"},
            },
            "required": ["type"],
            "additionalProperties": False,
        },
    },
    {
        "name": "three_d.object.remove",
        "description": "Remove a 3D object.",
        "inputSchema": {
            "type": "object",
            "properties": {"layer": {"type": "integer"}, "frame": {"type": "integer"}, "id": {"type": "integer"}},
            "required": ["id"],
            "additionalProperties": False,
        },
    },
    {
        "name": "three_d.object.update",
        "description": "Update a 3D object.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "frame": {"type": "integer"},
                "id": {"type": "integer"},
                "type": {"type": ["string", "integer"]},
                "position": {"type": "array"},
                "rotation": {"type": "array"},
                "rotation_degrees": {"type": "array"},
                "scale": {"type": "array"},
                "visible": {"type": "boolean"},
                "file_path": {"type": "string"},
            },
            "required": ["id"],
            "additionalProperties": False,
        },
    },
    {
        "name": "project.export.animated",
        "description": "Export animation as GIF/APNG.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "format": {"type": "string"},
                "tag": {"type": "string"},
                "tag_index": {"type": "integer"},
                "direction": {"type": "string"},
                "trim": {"type": "boolean"},
                "scale": {"type": "integer"},
                "interpolation": {"type": "string"},
                "split_layers": {"type": "boolean"},
                "erase_unselected_area": {"type": "boolean"},
            },
            "required": ["path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "project.export.spritesheet",
        "description": "Export spritesheet PNG.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "orientation": {"type": "string"},
                "lines": {"type": "integer"},
                "tag": {"type": "string"},
                "trim": {"type": "boolean"},
                "scale": {"type": "integer"},
                "interpolation": {"type": "string"},
            },
            "required": ["path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "layer.get_props",
        "description": "Get layer properties.",
        "inputSchema": {
            "type": "object",
            "properties": {"index": {"type": "integer"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "layer.set_props",
        "description": "Set layer properties (visible/locked/opacity/blend/clipping/name).",
        "inputSchema": {
            "type": "object",
            "properties": {
                "index": {"type": "integer"},
                "name": {"type": "string"},
                "visible": {"type": "boolean"},
                "locked": {"type": "boolean"},
                "opacity": {"type": "number"},
                "blend_mode": {"type": ["string", "integer"]},
                "clipping_mask": {"type": "boolean"},
            },
            "additionalProperties": False,
        },
    },
    {
        "name": "layer.group.create",
        "description": "Create a group layer.",
        "inputSchema": {
            "type": "object",
            "properties": {"above": {"type": "integer"}, "name": {"type": "string"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "layer.parent.set",
        "description": "Set layer parent (group).",
        "inputSchema": {
            "type": "object",
            "properties": {"index": {"type": "integer"}, "parent": {"type": "integer"}},
            "required": ["index"],
            "additionalProperties": False,
        },
    },
    {
        "name": "draw.text",
        "description": "Draw text onto a cel.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "text": {"type": "string"},
                "x": {"type": "integer"},
                "y": {"type": "integer"},
                "font_name": {"type": "string"},
                "size": {"type": "integer"},
                "align": {"type": "string"},
                "antialias": {"type": "boolean"},
                "color": {"type": ["array", "string", "object", "null"]},
                "width": {"type": "integer"},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["text", "x", "y"],
            "additionalProperties": False,
        },
    },
    {
        "name": "draw.gradient",
        "description": "Draw a linear gradient fill.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "x": {"type": "integer"},
                "y": {"type": "integer"},
                "width": {"type": "integer"},
                "height": {"type": "integer"},
                "from": {"type": ["array", "string", "object", "null"]},
                "to": {"type": ["array", "string", "object", "null"]},
                "direction": {"type": "string"},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["x", "y", "width", "height", "from", "to"],
            "additionalProperties": False,
        },
    },
    {
        "name": "animation.fps.get",
        "description": "Get animation FPS.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "animation.fps.set",
        "description": "Set animation FPS.",
        "inputSchema": {
            "type": "object",
            "properties": {"fps": {"type": "number"}},
            "required": ["fps"],
            "additionalProperties": False,
        },
    },
    {
        "name": "animation.frame_duration.set",
        "description": "Set frame duration (ms) for one or many frames.",
        "inputSchema": {
            "type": "object",
            "properties": {"frame": {"type": "integer"}, "duration_ms": {"type": "number"}, "durations_ms": {"type": "array"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "animation.loop.set",
        "description": "Set animation loop mode.",
        "inputSchema": {
            "type": "object",
            "properties": {"mode": {"type": "string"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "tilemap.fill_rect",
        "description": "Fill tilemap cells in a rect.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "frame": {"type": "integer"},
                "cell_x": {"type": "integer"},
                "cell_y": {"type": "integer"},
                "width": {"type": "integer"},
                "height": {"type": "integer"},
                "index": {"type": "integer"},
                "flip_h": {"type": "boolean"},
                "flip_v": {"type": "boolean"},
                "transpose": {"type": "boolean"},
            },
            "required": ["cell_x", "cell_y", "width", "height", "index"],
            "additionalProperties": False,
        },
    },
    {
        "name": "tilemap.replace_index",
        "description": "Replace tile index in tilemap.",
        "inputSchema": {
            "type": "object",
            "properties": {"layer": {"type": "integer"}, "frame": {"type": "integer"}, "from": {"type": "integer"}, "to": {"type": "integer"}},
            "required": ["from", "to"],
            "additionalProperties": False,
        },
    },
    {
        "name": "tilemap.random_fill",
        "description": "Random fill tilemap cells with weights.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "layer": {"type": "integer"},
                "frame": {"type": "integer"},
                "cell_x": {"type": "integer"},
                "cell_y": {"type": "integer"},
                "width": {"type": "integer"},
                "height": {"type": "integer"},
                "indices": {"type": "array"},
                "weights": {"type": "array"},
            },
            "required": ["cell_x", "cell_y", "width", "height", "indices"],
            "additionalProperties": False,
        },
    },
    {
        "name": "effect.shader.list",
        "description": "List built-in effect shaders.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "effect.shader.inspect",
        "description": "Inspect shader uniforms.",
        "inputSchema": {
            "type": "object",
            "properties": {"shader_path": {"type": "string"}},
            "required": ["shader_path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "effect.shader.schema",
        "description": "Get standardized shader parameter schema.",
        "inputSchema": {
            "type": "object",
            "properties": {"shader_path": {"type": "string"}},
            "required": ["shader_path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "brush.list",
        "description": "List project brushes.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "brush.add",
        "description": "Add a project brush from path or base64 PNG.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}, "data": {"type": "string"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "brush.remove",
        "description": "Remove a project brush by index.",
        "inputSchema": {
            "type": "object",
            "properties": {"index": {"type": "integer"}},
            "required": ["index"],
            "additionalProperties": False,
        },
    },
    {
        "name": "brush.clear",
        "description": "Clear all project brushes.",
        "inputSchema": {"type": "object", "properties": {}, "additionalProperties": False},
    },
    {
        "name": "brush.stamp",
        "description": "Stamp a brush at a position.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "x": {"type": "integer"},
                "y": {"type": "integer"},
                "brush_index": {"type": "integer"},
                "brush_type": {"type": "string"},
                "brush_path": {"type": "string"},
                "brush_data": {"type": "string"},
                "size": {"type": "integer"},
                "scale": {"type": "integer"},
                "color": {"type": ["array", "string", "object", "null"]},
                "opacity": {"type": "number"},
                "mode": {"type": "string"},
                "jitter": {"type": "number"},
                "spray": {"type": "integer"},
                "spray_radius": {"type": "number"},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["x", "y"],
            "additionalProperties": False,
        },
    },
    {
        "name": "brush.stroke",
        "description": "Draw a brush stroke along points.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "points": {"type": "array"},
                "brush_index": {"type": "integer"},
                "brush_type": {"type": "string"},
                "brush_path": {"type": "string"},
                "brush_data": {"type": "string"},
                "size": {"type": "integer"},
                "scale": {"type": "integer"},
                "color": {"type": ["array", "string", "object", "null"]},
                "opacity": {"type": "number"},
                "spacing": {"type": "number"},
                "spacing_curve": {"type": ["array", "string"]},
                "mode": {"type": "string"},
                "jitter": {"type": "number"},
                "spray": {"type": "integer"},
                "spray_radius": {"type": "number"},
                "frame": {"type": "integer"},
                "layer": {"type": "integer"},
            },
            "required": ["points"],
            "additionalProperties": False,
        },
    },
    {
        "name": "palette.import",
        "description": "Import a palette from file.",
        "inputSchema": {
            "type": "object",
            "properties": {"path": {"type": "string"}},
            "required": ["path"],
            "additionalProperties": False,
        },
    },
    {
        "name": "palette.export",
        "description": "Export a palette to file.",
        "inputSchema": {
            "type": "object",
            "properties": {"name": {"type": "string"}, "path": {"type": "string"}},
            "additionalProperties": False,
        },
    },
    {
        "name": "image.to_pixelart",
        "description": (
            "Convert a photo/image to pixel art. Accepts base64 image or file path, "
            "resizes to pixel art dimensions, reduces colors, and imports into Pixelorama."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "image_data": {"type": "string", "description": "Base64-encoded image (PNG/JPEG)"},
                "image_path": {"type": "string", "description": "Path to image file (alternative to image_data)"},
                "width": {"type": "integer", "default": 64, "description": "Target width in pixels"},
                "height": {"type": "integer", "default": 64, "description": "Target height in pixels"},
                "colors": {"type": "integer", "default": 0, "description": "Max colors (0 = no limit)"},
                "dither": {"type": "boolean", "default": False, "description": "Apply dithering during color reduction"},
                "project_name": {"type": "string", "default": "pixelart", "description": "Name for the new project"},
                "keep_aspect": {"type": "boolean", "default": True, "description": "Preserve aspect ratio (fit within width x height)"},
            },
            "additionalProperties": False,
        },
    },
]
